spring:
  application:
    name: academy-hero-quotes

server:
  port: 8082

hero:
  quotes:
    - "Мы все делаем выбор, но в конце концов выбор делает нас самих"
    - "Надежда делает нас сильными. Вот почему мы здесь. Это то, ради чего мы сражаемся, когда все остальное потеряно"
    - "Счастье — штука такая: пока оно есть, ты его не замечаешь. Ну, то есть можно убеждать себя, что счастлив. Но на самом деле в это не верить. Думать о повседневной мелочевке, о работе или еще о чем. Только оглядываясь назад и сравнивая настоящее с тем, что было раньше, ты понимаешь, что такое счастье"
    - "Каждый думает, что он герой своей собственной истории"
    - "Нужный человек не в том месте может перевернуть мир"
    - "Когда-то и меня вела дорога приключений. А потом мне прострелили колено…"
    - "Время жевать жвачку и драть задницы. Жвачка у меня кончилась"
    - "Счастье не купишь, зато можно купить много часов у психоаналитика, который в красках опишет, почему ты несчастлив."
    - "Победа в сражении - это самая незначительная победа. Победа без сражения - вот высочайшее мастерство"
    - "Прости, Джо в сделку не входил"
    - "И помните, ни слова по-русски"
    - "Короче, Меченый, я тебя спас и в благородство играть не буду: выполнишь для меня пару заданий — и мы в расчете. Заодно посмотрим, как быстро у тебя башка после амнезии прояснится. А по твоей теме постараюсь разузнать. Хрен его знает, на кой ляд тебе этот Стрелок сдался, но я в чужие дела не лезу, хочешь убить, значит есть за что…"
    - "Я уже говорил тебе, что такое безумие, а?"
    - "Проснитесь и пойте, мистер Фриман"
    - "Война. Война никогда не меняется"
    - "Я получил власть которая и не снилась моему отцу!"